//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rents
    {
        public int idRent { get; set; }
        public Nullable<int> idTanant { get; set; }
        public Nullable<int> idEmployee { get; set; }
        public string idPavilion { get; set; }
        public Nullable<int> idShopping { get; set; }
        public string statusRent { get; set; }
        public Nullable<System.DateTime> startRent { get; set; }
        public Nullable<System.DateTime> endRent { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Pavilions Pavilions { get; set; }
        public virtual Tanants Tanants { get; set; }
    }
}
